log:
  level: "debug"
  mode:  "dev"

server:
  shutdown_timeout: "15s"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "10s"

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database: "edrmvs"
  ssl_mode: "disable"

extractor:
  backoff: "1m"
  delay: "1s"

hsc:
  base_url: "https://mainapi.hsc.gov.ua"
  username: "opendata"
  password: "open_pass_bcrypt_data"

nats:
  nodes:
    - host: 0.0.0.0
      port: 4222
  user: "opencars"
  password: "opencars"