log:
  level: "debug"
  mode:  "dev"

server:
  shutdown_timeout: "15s"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "10s"

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database: "edrmvs"
  ssl_mode: "disable"

hsc:
  base_url: "http://api.hsc.gov.ua"
